### ISSUE TITLE
LabInABox.psm1 fixed resource names 

### ISSUE THREAD

**Issue by KenKilty** [Microsoft/DSC-data-driven-deployment#13]
LabInABox.psm1 has explicit string literals to resources whose name may change. Example: en_sql_server_2016_enterprise_x64_dvd_8701793.iso and PowerShell_6.0.0.14-alpha.14-win10-x64.msi.  For these sort of strings it may be worth marking the versions in the configuration in the likely event the names change when new versions are released. I would leave the more static resource names e.g. DSCResources.zip alone and out of the configuration.  Include only those resource strings likely to change such as the two above.

**Comment by aultt** [comment]
This was fixed in the latest change.
