### ISSUE TITLE
ISOs not listed in GUI

### ISSUE THREAD

**Issue by bush3102** [Microsoft/DSC-data-driven-deployment#26]
When initially starting LIAB, I click on 'FILE', then 'OPEN' and choose the 'Default_Private_Config.json' located under: C:\Program Files\LabInaBox\LabConfig

From there, the drop downs are blank.
![screen_shot_4](https://cloud.githubusercontent.com/assets/14627969/25722259/7e0161c4-30e1-11e7-91b4-1dec8feb6cd9.jpg)
![screen_shot_5](https://cloud.githubusercontent.com/assets/14627969/25722258/7df43d6e-30e1-11e7-8d78-4a1cf194cff8.jpg)

**Comment by aultt** [comment]
An update has been published to the Dev branch which should correct this behavior.  Included is an installer which should install all the files needed for LabInabox in to the Program Files folder.  Please let me know if this fixes this and we can close the issue.  Thanks
