### ISSUE TITLE
[Enhancement]Request for CORE builds

### ISSUE THREAD

**Issue by forensicsguy20012004** [Microsoft/DSC-data-driven-deployment#27]
I as a user would like the ability to 'build' desktops/servers using a CORE build. The reason I am asking, it will help familiarize individuals that have never used CORE before a place to play. Thanks

**Comment by aultt** [comment]
This capability exists today.  To leverage you need a sysprepped CORE image.  Once you have this image you reference this in your lab configuration any vms which you build will be windows core.  If you want a mix build one then add additional vms once first is done and change to CORE then run update-script and new machines should be built using CORE

**Comment by forensicsguy20012004** [comment]
thanks troy... :)
